### PR TITLE
User Management -Backend part

### PR DESCRIPTION
**Pull request by coderahmadi**
Hey dear collaborators!
here is my update about a user (Model, Controller, Routes) and Validation and Sanitization.

### CODE REVIEW

**Comment by Chandu-Sasidharan** [comment]
@Jamal Thank you for the update. I have a few comments
- Why is there a separate validator for each property? Isn't one validator like a userValidator enough?
- I can see you created so many end points like findByEmailAndUpdate, findByIdAndUpdate etc. Are all these end points required? Have you guys have a plan for the frontend?
- The validations isn't taking place yet

**Comment by coderahmadi** [comment]
@Chandu-Sasidharan, thanks Chandu for your review, I reply in the above order.
- we can declare an array for each Schema (User, Contact, Tree, etc) and put the validator of all fields of a specific Schema inside it. Gilles recommended using separate functions for each field. also, separate files for each Schema.
- though finding by ID and email are duplicate way. but I think we will need it for the Admin Panel. because the Admin needs to have more freedom to change data in different ways. our next step is to start designing and developing the front end and Admin Panel.
- The validations isn't taking place yet?
  I was using INSOMNIA to test the validations and sanitization of user parts. hopefully, it works.

**Comment by Chandu-Sasidharan** [comment]
Hi Jamal,

Thank you for the update. Here are my comments/observations:

- URLs typically use lowercase letters to avoid case sensitivity issues. For example, use `change-password` instead of `changePassword`.
- Let's adhere to RESTful conventions by simplifying route names, as the HTTP method already implies the action:
  - `user/createUser` => (POST) `user/`
  - `user/getAllUsers` => (GET) `user/`
  - ...and so on.
- The email validator includes a check for an existing email, which is great for creating a new user. However, for updates, we should exclude the current user's email to prevent false positives.
- In the login controller, `bcrypt.compare()` is asynchronous and should be used with `await`.
- When authentication fails in the login process, the status code should be 401 Unauthorized, not 404 Not Found.
- For enhanced security, consider implementing short-lived tokens with a refresh mechanism and invalidate tokens upon sign-out.
- It seems we have both `updateById` and `updateAllField` routes that find and update users by ID. Could we consolidate these to avoid redundancy?
- Route parameters like `uId` should be validated to ensure they meet our expected format and type.
- In the `updateAllField` function, ensure that passwords are not saved as plain text. They should be hashed before storing in the database.
- The `changingPassword` function appears incomplete and better renamed to `changePassword`.
- For cookie security, use an environment variable to set the `secure` option, like so: `secure: process.env.NODE_ENV === 'production'`. This ensures cookies are sent over HTTPS in production.
- Lastly, as previously discussed, exporting all user property validators as an array from the userValidator module and then using it in the route would be cleaner and more maintainable.

Looking forward to the revisions!

**Comment by coderahmadi** [comment]
@Chandu-Sasidharan, Changes Applied!

**Comment by Chandu-Sasidharan** [comment]
@coderahmadi  I forget to add one point, for better security we should also add salt to the password hash.
By the way if you disagree with any of the previous points, lets discuss that tomorrow :)

**Comment by Chandu-Sasidharan** [comment]
> @Chandu-Sasidharan, Changes Applied!

Oh pushed some changes now, let me check it

**Review by Chandu-Sasidharan — APPROVED** [review]

**Pull request merged**
