### PR TITLE
created basic tree schema with add,delete,update fucnctions etc

### PR DESCRIPTION
**Pull request by SimonDavidMurray**
Hope this is correct so far. Will need to update the schema to include tree name etc. Will also need to change the status code code as we have not yet installed http-status-codes (that is if we intend to use it)

### CODE REVIEW

**Comment by Chandu-Sasidharan** [comment]
All looking good Simon! and about the http-status-codes package, it doesn't really matter to use it or not, but if you guys decide to use it, then everybody use it to make things consistent. I see @Shaqayeq-taheri is already using it, then you may also use it

**Review by coderahmadi — CHANGES_REQUESTED** [review]
@SimonDavidMurray, thanks Simon for your update. following are some points I need to mention.
1. In Tree.js, for creating schema you have defined "children" property that is referenced to model name "Tree".  I think we don't need it. hence we are currently inside "Tree" schema. instead you can put "name" or "number" that specifies the tree name or number.
- also, inside Controller.js we need to remove .populate() method. 
we can do it tommorrow on live-coding.

**Comment by Chandu-Sasidharan** [comment]
I have updated the schema, routes and controllers.

Pending work:
- Data Validation
- Using http-status-codes package

**Review by coderahmadi — APPROVED** [review]
@SimonDavidMurray , @Chandu-Sasidharan, every parts are done without any issue. Thanks Simon!

**Review by Chandu-Sasidharan — APPROVED** [review]

**Pull request merged**
